models:
  logistic_l2:
    C: [0.01, 1.0]
    penalty: 'l2'
    solver: 'lbfgs'
    max_iter: 1000
  random_forest:
    n_estimators: [50, 100]
    max_depth: [3, 5]
  xgboost:
    max_depth: [2, 3]
    min_child_weight: [1.0]
    reg_lambda: [1.0]
    learning_rate: [0.1]
    n_estimators: [50]
  lightgbm:
    max_depth: [2, 3]
    num_leaves: [7]
    reg_lambda: [1.0]
    learning_rate: [0.1]
    n_estimators: [50]
